service: slack-app
provider: 
  name: aws
  runtime: nodejs12.x
  region: us-east-1
  role: arn:aws:iam::720145052241:role/Slack
  timeout: 5
  stage: ${opt:stage, 'dev'}
  memorySize: 128
functions:
  dispatcher:
    handler: bot.run
    description: description
    exclude:
      - package-lock.json
    optimize: true
    events:
      - http:
          path: "/events"
          method: post 